version: '3'

services:
  nginx:
    container_name: infisical-dev-nginx
    image: nginx
    restart: always
    ports:
      - 8080:80
    volumes:
      - ./nginx/default.dev.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - frontend
      - backend
    networks:
      - infisical-dev

  backend:
    container_name: infisical-dev-backend
    image: 258184935805.dkr.ecr.us-east-1.amazonaws.com/kranio-infisical-backend:latest
    restart: unless-stopped
    depends_on:
      - smtp-server
    environment:
      - NEXT_PUBLIC_ENV=${NEXT_PUBLIC_ENV}
      - INFISICAL_TELEMETRY_ENABLED=${INFISICAL_TELEMETRY_ENABLED}
      - NEXT_PUBLIC_STRIPE_PRODUCT_PRO=${NEXT_PUBLIC_STRIPE_PRODUCT_PRO}
      - NEXT_PUBLIC_STRIPE_PRODUCT_TEAM=${NEXT_PUBLIC_STRIPE_PRODUCT_TEAM}
      - NEXT_PUBLIC_STRIPE_PRODUCT_STARTER=${NEXT_PUBLIC_STRIPE_PRODUCT_STARTER}
      - SITE_URL=${SITE_URL}
      - NODE_ENV=${NODE_ENV}
      - ENCRYPTION_KEY=${ENCRYPTION_KEY}
      - JWT_SIGNUP_SECRET=${JWT_SIGNUP_SECRET}
      - JWT_REFRESH_SECRET=${JWT_REFRESH_SECRET}
      - JWT_AUTH_SECRET=${JWT_AUTH_SECRET}
      - JWT_SERVICE_SECRET=${JWT_SERVICE_SECRET}
      - JWT_AUTH_LIFETIME=${JWT_AUTH_LIFETIME}
      - JWT_REFRESH_LIFETIME=${JWT_REFRESH_LIFETIME}
      - JWT_SIGNUP_LIFETIME=${JWT_SIGNUP_LIFETIME}
      - MONGO_URL=${MONGO_URL}
      - MONGO_USERNAME=${MONGO_USERNAME}
      - MONGO_PASSWORD=${MONGO_PASSWORD}
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_USERNAME=${SMTP_USERNAME}
      - SMTP_PASSWORD=${SMTP_PASSWORD}
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_SECURE=${SMTP_SECURE}
      - SMTP_FROM_ADDRESS=${SMTP_FROM_ADDRESS}
      - SMTP_FROM_NAME=${SMTP_FROM_NAME}
      - CLIENT_ID_HEROKU=${CLIENT_ID_HEROKU}
      - CLIENT_ID_VERCEL=${CLIENT_ID_VERCEL}
      - CLIENT_ID_NETLIFY=${CLIENT_ID_NETLIFY}
      - CLIENT_ID_GITHUB=${CLIENT_ID_GITHUB}
      - CLIENT_ID_GITLAB=${CLIENT_ID_GITLAB}
      - CLIENT_SECRET_HEROKU=${CLIENT_SECRET_HEROKU}
      - CLIENT_SECRET_VERCEL=${CLIENT_SECRET_VERCEL}
      - CLIENT_SECRET_NETLIFY=${CLIENT_SECRET_NETLIFY}
      - CLIENT_SECRET_GITHUB=${CLIENT_SECRET_GITHUB}
      - CLIENT_SECRET_GITLAB=${CLIENT_SECRET_GITLAB}
      - CLIENT_SLUG_VERCEL=${CLIENT_SLUG_VERCEL}
      - SENTRY_DSN=${SENTRY_DSN}
      - POSTHOG_HOST=${POSTHOG_HOST}
      - POSTHOG_PROJECT_API_KEY=${POSTHOG_PROJECT_API_KEY}
      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
      - STRIPE_PUBLISHABLE_KEY=${STRIPE_PUBLISHABLE_KEY}
      - STRIPE_WEBHOOK_SECRET=${STRIPE_WEBHOOK_SECRET}
      - STRIPE_PRODUCT_STARTER=${STRIPE_PRODUCT_STARTER}
      - STRIPE_PRODUCT_TEAM=${STRIPE_PRODUCT_TEAM}
      - STRIPE_PRODUCT_PRO=${STRIPE_PRODUCT_PRO}
      - NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY=${NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY}
      - TELEMETRY_ENABLED=${TELEMETRY_ENABLED}
      - TELEMETRY_CAPTURING_ENABLED=${TELEMETRY_CAPTURING_ENABLED}
    networks:
      - infisical-dev

  frontend:
    container_name: infisical-dev-frontend
    image: 258184935805.dkr.ecr.us-east-1.amazonaws.com/kranio-infisical-frontend:latest
    restart: unless-stopped
    depends_on:
      - backend
    environment:
      - NEXT_PUBLIC_ENV=${NEXT_PUBLIC_ENV}
      - INFISICAL_TELEMETRY_ENABLED=${INFISICAL_TELEMETRY_ENABLED}
      - NEXT_PUBLIC_STRIPE_PRODUCT_PRO=${NEXT_PUBLIC_STRIPE_PRODUCT_PRO}
      - NEXT_PUBLIC_STRIPE_PRODUCT_TEAM=${NEXT_PUBLIC_STRIPE_PRODUCT_TEAM}
      - NEXT_PUBLIC_STRIPE_PRODUCT_STARTER=${NEXT_PUBLIC_STRIPE_PRODUCT_STARTER}
      - SITE_URL=${SITE_URL}
      - NODE_ENV=${NODE_ENV}
      - ENCRYPTION_KEY=${ENCRYPTION_KEY}
      - JWT_SIGNUP_SECRET=${JWT_SIGNUP_SECRET}
      - JWT_REFRESH_SECRET=${JWT_REFRESH_SECRET}
      - JWT_AUTH_SECRET=${JWT_AUTH_SECRET}
      - JWT_SERVICE_SECRET=${JWT_SERVICE_SECRET}
      - JWT_AUTH_LIFETIME=${JWT_AUTH_LIFETIME}
      - JWT_REFRESH_LIFETIME=${JWT_REFRESH_LIFETIME}
      - JWT_SIGNUP_LIFETIME=${JWT_SIGNUP_LIFETIME}
      - MONGO_URL=${MONGO_URL}
      - MONGO_USERNAME=${MONGO_USERNAME}
      - MONGO_PASSWORD=${MONGO_PASSWORD}
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_USERNAME=${SMTP_USERNAME}
      - SMTP_PASSWORD=${SMTP_PASSWORD}
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_SECURE=${SMTP_SECURE}
      - SMTP_FROM_ADDRESS=${SMTP_FROM_ADDRESS}
      - SMTP_FROM_NAME=${SMTP_FROM_NAME}
      - CLIENT_ID_HEROKU=${CLIENT_ID_HEROKU}
      - CLIENT_ID_VERCEL=${CLIENT_ID_VERCEL}
      - CLIENT_ID_NETLIFY=${CLIENT_ID_NETLIFY}
      - CLIENT_ID_GITHUB=${CLIENT_ID_GITHUB}
      - CLIENT_ID_GITLAB=${CLIENT_ID_GITLAB}
      - CLIENT_SECRET_HEROKU=${CLIENT_SECRET_HEROKU}
      - CLIENT_SECRET_VERCEL=${CLIENT_SECRET_VERCEL}
      - CLIENT_SECRET_NETLIFY=${CLIENT_SECRET_NETLIFY}
      - CLIENT_SECRET_GITHUB=${CLIENT_SECRET_GITHUB}
      - CLIENT_SECRET_GITLAB=${CLIENT_SECRET_GITLAB}
      - CLIENT_SLUG_VERCEL=${CLIENT_SLUG_VERCEL}
      - SENTRY_DSN=${SENTRY_DSN}
      - POSTHOG_HOST=${POSTHOG_HOST}
      - POSTHOG_PROJECT_API_KEY=${POSTHOG_PROJECT_API_KEY}
      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
      - STRIPE_PUBLISHABLE_KEY=${STRIPE_PUBLISHABLE_KEY}
      - STRIPE_WEBHOOK_SECRET=${STRIPE_WEBHOOK_SECRET}
      - STRIPE_PRODUCT_STARTER=${STRIPE_PRODUCT_STARTER}
      - STRIPE_PRODUCT_TEAM=${STRIPE_PRODUCT_TEAM}
      - STRIPE_PRODUCT_PRO=${STRIPE_PRODUCT_PRO}
      - NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY=${NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY}
      - TELEMETRY_ENABLED=${TELEMETRY_ENABLED}
      - TELEMETRY_CAPTURING_ENABLED=${TELEMETRY_CAPTURING_ENABLED}
    networks:
      - infisical-dev

  smtp-server:
    container_name: infisical-dev-smtp-server
    image: lytrax/mailhog:latest
    restart: always
    logging:
      driver: 'none' # disable saving logs
    ports:
      - 1025:1025 # SMTP server
      - 8025:8025 # Web UI
    networks:
      - infisical-dev

networks:
  infisical-dev:
